### ISSUE TITLE
Application Override

### ISSUE THREAD

**Issue by alabotski** [samolego/Canta#31] opened 2024-02-06 04:43 UTC
**Describe the bug**
Canta does not see all applications that are installed on the system

**To Reproduce**
1. I use LineageOS and it firmware has 2 default app (as example) calendar & clock
2. I run Canta  and all works fine. Canta finds them. 
[Screenshot_20240205-213020_Canta](https://github.com/samolego/Canta/assets/439337/547d562e-5c32-43ba-9bca-45b8e754a66a)
[Screenshot_20240205-213040_Canta](https://github.com/samolego/Canta/assets/439337/1793941c-f1f6-4e0f-ab03-42d0a752cc78)
3. Then I install the same app by google. https://play.google.com/store/apps/details?id=com.google.android.deskclock&hl=en_US and 
https://play.google.com/store/apps/details?id=com.google.android.calculator&hl=en_US
4. Go to Canta search and try find clock or calculator. I can find olny app by Google

**Expected behavior**
Display all applications installed on the system

**Version info**
 - Android version: 14
 - Canta version: 1.2.1
 - Shizuku version: 13.5.3.r1040.1fc3a2d

**Logcat**

**Comment by samolego** [comment] 2024-02-06 06:51
This is a duplicate of #21

**Closed by samolego** 2024-02-06 06:51 UTC
Labels: bug
