### ISSUE TITLE
Google Calendar is not showing in list

### ISSUE THREAD

**Issue by Deepak99559** [samolego/Canta#54] opened 2024-04-15 03:40 UTC
**Describe the bug**
I try to uninstall all Google apps from my device and I already uninstall most of Google apps from my device but not able to uninstall Google Calendar because it is not showing in the list.

**To Reproduce**

**Expected behavior**
I want to uninstall Google Calendar because I already found it's alternative.

**Version info**
 - Android version: 14
 - Canta version: 1.4.1
 - Shizuku version: 13.5.4.r1049.0e53409

**Logcat**

<details>
  <summary>View logcat</summary>
  ```logcat
  paste logcat here
  ```
</details>

**Comment by samolego** [comment] 2024-04-15 04:44
Is "calendar" app installed? If so, that's duplicate of #21

**Comment by Deepak99559** [comment] 2024-04-15 11:10
Yes I recheck the name of both app. On Playstore it is showing Google Calendar and in app drawer it is showing only Calendar and same with Fossify calendar. When I uninstall Fossify calendar and then open Canta then I finally saw Google Calendar and finally I uninstall Google Calendar. You are right, both app names are displaying as Calendar in app drawer. Thank you my dear friend for help ❤️

**Closed** 2024-04-15 11:11 UTC
Labels: bug

**Comment by samolego** [comment] 2024-04-15 15:22
No problem, glad it worked for you :)!
