### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by variety754** [samolego/Canta#57] opened 2024-04-28 06:02 UTC
**Describe the bug**
When I load into app "Loading app..." is an infinite loading screen. Before everything was working, but a random day this issue appeared

**To Reproduce**
1. Start the app
2. See the infinite loading screen

**Expected behavior**
Apps being shown

**Version info**
 - Android version: 13
 - Canta version: 1.4.1
 - Shizuku version: 13.5.4.r.1049

**Logcat**
I don't know what this is

**Comment by samolego** [comment] 2024-04-28 17:21
Duplicate of #3

**Closed by samolego** 2024-04-28 17:21 UTC
Labels: bug
